# This is a basic workflow to help you get started with Actions

name: DeployBot

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  deployment:
    if: github.actor != 'dependabot[bot]'
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - run: echo "${{github.actor}}"
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - name: Installing NPM packages
      run: npm install
    - name: Running verifications
      run: npm run pre-deploy
    - name: Deploying version
      uses: danitseitlin/package-deployer@master
      with:
        pkg_name: cli-argument-parser
        main_pkg_manager: npm
        pkg_managers: '[github, npm]'
        npm_registry: registry.npmjs.org
        npm_access_token: ${{secrets.NPM_AUTH_TOKEN}}
        github_access_token: ${{secrets.G_AUTH_TOKEN}}
        pretty_print: true
